# Generated by Django 3.0.5 on 2020-07-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('interface_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=50)),
                ('mask', models.CharField(max_length=50)),
                ('gateway', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.Component')),
                ('router_id', models.AutoField(primary_key=True, serialize=False)),
                ('operative_system', models.CharField(max_length=50)),
            ],
            bases=('api.component',),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.Component')),
                ('switch_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('api.component',),
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='api.Component')),
                ('workstation_id', models.AutoField(primary_key=True, serialize=False)),
                ('operative_system', models.CharField(max_length=50)),
            ],
            bases=('api.component',),
        ),
        migrations.RemoveField(
            model_name='component',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='component',
            name='position_y',
        ),
        migrations.CreateModel(
            name='RouteTable',
            fields=[
                ('route_table_id', models.AutoField(primary_key=True, serialize=False)),
                ('subnet_mask', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('metric', models.IntegerField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Interface')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkComponent',
            fields=[
                ('network_component_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_x', models.CharField(max_length=50)),
                ('position_y', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=50)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Component')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Network')),
            ],
        ),
        migrations.AddField(
            model_name='interface',
            name='network_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.NetworkComponent'),
        ),
    ]
