# Generated by Django 3.0.5 on 2020-07-14 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200714_1147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RouteTable',
            new_name='RoutingTable',
        ),
    ]
