# Generated by Django 3.0.5 on 2020-07-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200714_2318'),
    ]

    operations = [
    ]
