# Generated by Django 4.1.7 on 2025-06-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210412_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
