# Generated by Django 4.1.7 on 2025-09-04 22:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_network_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=16)),
                ('task_id', models.CharField(blank=True, max_length=64, null=True)),
                ('s3_key', models.CharField(blank=True, default='', max_length=256)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='interface',
            name='network_component',
        ),
        migrations.RemoveField(
            model_name='network',
            name='cloud',
        ),
        migrations.RemoveField(
            model_name='networkcomponent',
            name='component',
        ),
        migrations.RemoveField(
            model_name='networkcomponent',
            name='network',
        ),
        migrations.RemoveField(
            model_name='router',
            name='component_ptr',
        ),
        migrations.RemoveField(
            model_name='routingtable',
            name='interface',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='component_ptr',
        ),
        migrations.RemoveField(
            model_name='workstation',
            name='component_ptr',
        ),
        migrations.DeleteModel(
            name='Cloud',
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Interface',
        ),
        migrations.DeleteModel(
            name='Network',
        ),
        migrations.DeleteModel(
            name='NetworkComponent',
        ),
        migrations.DeleteModel(
            name='Router',
        ),
        migrations.DeleteModel(
            name='RoutingTable',
        ),
        migrations.DeleteModel(
            name='Switch',
        ),
        migrations.DeleteModel(
            name='Workstation',
        ),
    ]
