# Generated by Django 4.1.7 on 2026-01-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_plan_remove_interface_network_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='firestore_vpc_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
