# Generated by Django 4.1.7 on 2026-01-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_plan_firestore_vpc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='last_action',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
