# Generated by Django 4.1.7 on 2026-01-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_plan_applied_plan_last_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='outputs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
