# Generated by Django 4.1.7 on 2026-01-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_plan_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='last_outputs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
