# Generated by Django 4.1.7 on 2026-01-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_plan_last_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='last_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plan',
            name='last_log_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
