# Generated by Django 4.1.7 on 2026-01-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_plan_last_log_plan_last_log_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='last_deploy_task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='last_destroy_task_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
