# Generated by Django 4.1.7 on 2026-01-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_plan_last_deploy_task_id_plan_last_destroy_task_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='last_outputs',
        ),
        migrations.AlterField(
            model_name='plan',
            name='applied',
            field=models.BooleanField(default=False, help_text='True si la última ejecución fue un APPLY real (infra creada).'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='firestore_vpc_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='last_action',
            field=models.CharField(blank=True, choices=[('plan', 'Plan'), ('apply', 'Apply'), ('destroy', 'Destroy')], default='', help_text='Última acción ejecutada sobre este plan: "plan" | "apply" | "destroy"', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='last_deploy_task_id',
            field=models.CharField(blank=True, help_text='task_id de la última ejecución deploy (plan/apply).', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='last_destroy_task_id',
            field=models.CharField(blank=True, help_text='task_id de la última ejecución destroy.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='last_log',
            field=models.TextField(blank=True, default='', help_text='Log unificado de la última ejecución (plan/apply/destroy).'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='last_log_updated_at',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora de la última actualización de last_log.', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='outputs',
            field=models.JSONField(blank=True, default=dict, help_text='Últimos outputs conocidos (después de APPLY o del último RUN).', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='s3_key',
            field=models.CharField(blank=True, default='', help_text='(Reservado) Key de logs en S3. En DEV/local se usa last_log en DB.', max_length=256),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], db_index=True, default='PENDING', help_text='Estado actual del plan: PENDING | RUNNING | SUCCESS | FAILURE', max_length=16),
        ),
        migrations.AlterField(
            model_name='plan',
            name='task_id',
            field=models.CharField(blank=True, help_text='Última task_id (compat). Preferir last_deploy_task_id / last_destroy_task_id.', max_length=64, null=True),
        ),
    ]
