# Generated by Django 4.1.7 on 2026-01-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_plan_options_remove_plan_last_outputs_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('firestore_vpc_id__isnull', False)), fields=('firestore_vpc_id',), name='uniq_plan_firestore_vpc_id'),
        ),
    ]
