# Generated by Django 4.1.7 on 2026-01-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_plan_uniq_plan_firestore_vpc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='canvas_hash',
            field=models.CharField(blank=True, db_index=True, help_text='Hash del canvas/payload para detectar cambios sin comparar todo.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='canvas_updated_at',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora del último sync desde el canvas (frontend/Firestore).', null=True),
        ),
    ]
