# Generated by Django 4.1.7 on 2026-03-12 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_plan_canvas_hash_plan_canvas_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='plan',
            name='applied',
            field=models.BooleanField(default=False, help_text='True si la ultima ejecucion fue un APPLY real (infra creada).'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='canvas_updated_at',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora del ultimo sync desde el canvas.', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='firestore_vpc_id',
            field=models.CharField(blank=True, db_index=True, help_text='Legacy canvas id. Mantener por compatibilidad mientras se migra el frontend.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='last_action',
            field=models.CharField(blank=True, choices=[('plan', 'Plan'), ('apply', 'Apply'), ('destroy', 'Destroy'), ('canvas_update', 'Canvas Update')], default='', help_text='Ultima accion ejecutada sobre este plan: "plan" | "apply" | "destroy" | "canvas_update"', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='last_deploy_task_id',
            field=models.CharField(blank=True, help_text='task_id de la ultima ejecucion deploy (plan/apply).', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='last_destroy_task_id',
            field=models.CharField(blank=True, help_text='task_id de la ultima ejecucion destroy.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='last_log',
            field=models.TextField(blank=True, default='', help_text='Log unificado de la ultima ejecucion (plan/apply/destroy).'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='last_log_updated_at',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora de la ultima actualizacion de last_log.', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='outputs',
            field=models.JSONField(blank=True, default=dict, help_text='Ultimos outputs conocidos (despues de APPLY o del ultimo RUN).', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='task_id',
            field=models.CharField(blank=True, help_text='Ultima task_id (compat). Preferir last_deploy_task_id / last_destroy_task_id.', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('platform_admin', 'Platform Admin'), ('teacher', 'Teacher'), ('student', 'Student')], db_index=True, default='student', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('deactivated', 'Deactivated')], db_index=True, default='pending', max_length=32)),
                ('photo_url', models.URLField(blank=True, default='')),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('google_sub', models.CharField(blank=True, default='', max_length=255)),
                ('invite_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('invitation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.course')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_profiles', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('visibility_scope', models.CharField(choices=[('owner', 'Owner'), ('course', 'Course')], db_index=True, default='owner', max_length=16)),
                ('created_by_role', models.CharField(default='student', max_length=32)),
                ('target_provider', models.CharField(choices=[('aws', 'AWS'), ('gcp', 'GCP'), ('azure', 'Azure')], db_index=True, default='aws', max_length=16)),
                ('flow', models.JSONField(blank=True, default=dict)),
                ('intent', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('provider_overrides', models.JSONField(blank=True, default=dict)),
                ('cidr_block', models.CharField(blank=True, default='', max_length=64)),
                ('prefix_length', models.IntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, default='', max_length=32)),
                ('narrative', models.CharField(blank=True, default='advanced', max_length=32)),
                ('lab_template', models.CharField(blank=True, default='', max_length=128)),
                ('legacy_canvas_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('plan_canvas_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labs', to='api.course')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AmiCatalogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=128, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('provider', models.CharField(choices=[('aws', 'AWS'), ('gcp', 'GCP'), ('azure', 'Azure')], default='aws', max_length=16)),
                ('region', models.CharField(blank=True, default='', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ami_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'region', 'code'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='api.lab'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('teacher', 'name'), name='uniq_course_name_per_teacher'),
        ),
    ]
