# Generated by Django 4.1.7 on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_rename_plan_firestore_vpc_id_to_canvas_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lab",
            name="legacy_canvas_id",
            field=models.CharField(
                blank=True,
                help_text="Alias legacy del canvas. Se mantiene por compatibilidad con ids historicos ya emitidos.",
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
    ]
