# Generated by Django 4.1.7 on 2026-04-06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_lab_legacy_canvas_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudConnection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("provider", models.CharField(choices=[("aws", "AWS"), ("gcp", "GCP"), ("azure", "Azure")], db_index=True, default="aws", max_length=16)),
                ("scope", models.CharField(choices=[("personal", "Personal"), ("course_shared", "Course Shared")], db_index=True, default="personal", max_length=24)),
                ("auth_type", models.CharField(choices=[("aws_static_keys", "AWS Static Keys")], default="aws_static_keys", max_length=32)),
                ("default_region", models.CharField(blank=True, default="", max_length=32)),
                ("aws_access_key_id", models.CharField(blank=True, default="", max_length=128)),
                ("aws_secret_access_key_encrypted", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_test_status", models.CharField(blank=True, default="", max_length=24)),
                ("last_test_message", models.TextField(blank=True, default="")),
                ("last_test_identity", models.JSONField(blank=True, default=dict)),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("course", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="cloud_connections", to="api.course")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_cloud_connections", to=settings.AUTH_USER_MODEL)),
                ("owner_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="cloud_connections", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["name", "-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="lab",
            name="cloud_connection",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="labs", to="api.cloudconnection"),
        ),
    ]
