# Generated by Django 4.1.7 on 2026-04-15 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0027_execution_history_and_delegations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planexecutionrecord',
            name='action',
            field=models.CharField(choices=[('plan', 'Plan'), ('apply', 'Apply'), ('destroy', 'Destroy'), ('canvas_update', 'Canvas Update')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='KeyPairCatalogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('label', models.CharField(blank=True, default='', max_length=128)),
                ('provider', models.CharField(choices=[('aws', 'AWS'), ('gcp', 'GCP'), ('azure', 'Azure')], default='aws', max_length=16)),
                ('region', models.CharField(blank=True, default='', max_length=32)),
                ('scope', models.CharField(choices=[('personal', 'Personal'), ('course_shared', 'Course Shared')], db_index=True, default='personal', max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloud_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_pair_entries', to='api.cloudconnection')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_pair_entries', to='api.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_key_pair_entries', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_pair_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'scope', 'region', 'name'],
            },
        ),
    ]
